name: Automated Tests for find_lowest_number.py

on:
  push:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Pyhton
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run Test 1
        run: |
          pyhton3 find_lowest_number.py test_data/test1_input.txt test1_output.txt
          diff test1_output.txt test_data/test1_expected.txt

      - name: Run Test 2
        run: |
          python3 find_lowest_number.py test_data/test2_input.txt test2_output.txt
          diff test2_output.txt test_data/test2_expected.txt

      - name: Run Test 3
        run: |
          python3 find_lowest_number.py test_data/test3_input.txt test3_output.txt
          diff test3_output.txt test_data/test3_expected.txt
      
